version: "3.8"

services:
  user-app:
    container_name: "user-app"
    image: paytm-project-starter-monorepo-user-app
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network

    env_file:
      - ./.env
    depends_on:
      - bank-webhook
 

  bank-webhook:
    container_name: "bank-webhook"
    image: paytm-project-starter-monorepo-bank-webhook  
    restart: always
    ports:
      - 3002:3002
    env_file:
      - ./.env
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
    driver: bridge