version: "3.8"

services:
  user-app:
    container_name: "user-app"
    build:
      context: .
      dockerfile: ./apps/user-app/Dockerfile.user

    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./.env

    depends_on:
      - bank-webhook
  bank-webhook:
    container_name: "bank-webhook"
    build:
      context: .
      dockerfile: ./apps/bank-webhook/Dockerfile.webhook

    restart: always
    ports:
      - 3001:3001
    env_file:
       - ./.env
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
    driver: bridge