version: "3.8"

services:
  user-app:
    container_name: "user-app"
    image: codewithjass/wallet_app:user-app
    restart: always
    ports:
      - 3002:3002
    networks:
      - app_network
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - ./.env
    depends_on:
      - bank-webhook
 

  bank-webhook:
    container_name: "bank-webhook"
    image: codewithjass/wallet_app:bank-webhook
    restart: always
    ports:
      - 3001:3001
    volumes:
     - ./:/app/
     - /app/node_modules/
    env_file:
      - ./.env
    environment:
      PORT_EXPRESS_WEBHOOK: ${PORT_EXPRESS_WEBHOOK}
      DATABASE_URL: ${DATABASE_URL}

    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true
    driver: bridge