version: "3.8"

services:
  turbo:
    image: codewithjass/wallet_app:latest
    ports:
      - "3001:3001"
      - "3002:3002"
    env_file:
      - ../.env
    environment:
      - NODE_ENV=production
  
    restart: on-failure
     
    
 