name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push User Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/user-app/Docker/Dockerfile.user
          push: true
          tags: codewithjass/wallet_app:user-app
          build-args: |
            DATABASE_URL=${{secrets.DATABASE_URL}}

      - name: Build and Push Bank webhook Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/bank-webhook/Dockerfile.webhook
          push: true
          tags: codewithjass/wallet_app:bank-webhook
          build-args: |
            DATABASE_URL=${{secrets.DATABASE_URL}}

      - name: Verify wallet_app Pushed Image
        run: docker pull codewithjass/wallet_app:user-app

      - name: Verify Pushed Image
        run: docker pull codewithjass/wallet_app:bank-webhook

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_WALLET_HOST }}
          username: ${{ secrets.SSH_WALLET_USERNAME }}
          key: ${{ secrets.SSH_WALLET_KEY }}
          script: |
            cd walletApp
            sudo docker-compose down
            sudo docker rm -f $(docker ps -a -q) 
            sudo docker rmi -f codewithjass/wallet_app:user-app || true
            sudo docker rmi -f codewithjass/wallet_app:bank-webhook || true
            sudo docker volume rm $(docker volume ls -q)
            sudo docker pull codewithjass/wallet_app:user-app || true
            sudo docker pull codewithjass/wallet_app:bank-webhook || true
            sudo docker network inspect app_network >/dev/null 2>&1 || sudo docker network create app_network
            sudo docker-compose up -d
