name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: codewithjass/wallet_app:latest # Replace with your Docker Hub username and repository

      - name: Verify Pushed Image
        run: docker pull codewithjass/wallet_app:latest # Replaces with your Docker Hub username and repository

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_WALLET_HOST }}
          username: ${{ secrets.SSH_WALLET_USERNAME }}
          key: ${{ secrets.SSH_WALLET_KEY }}
          script: |
            sudo docker pull codewithjass/wallet_app:latest
            sudo docker stop wallet_app || true
            sudo docker rm wallet_app || true
            sudo docker run -d --env-file /home/ubuntu/walletApp/.env --name wallet_app -p 3001:3001 -p 3002:3002 codewithjass/wallet_app:latest
