name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push User Docker image
        uses: docker/build-push-action@v2
        with:
           context: .
          file: ./apps/user-app/Dockerfile.user
          push: true
          tags: codewithjass/wallet_app:user-app

      - name: Build and Push Bank webhook Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/bank-webhook/Dockerfile.webhook
          push: true
          tags: codewithjass/wallet_app:bank-webhook

      - name: Verify wallet_app Pushed Image
        run: docker pull codewithjass/wallet_app:user-app

      - name: Verify Pushed Image
        run: docker pull codewithjass/wallet_app:bank-webhook

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_WALLET_HOST }}
          username: ${{ secrets.SSH_WALLET_USERNAME }}
          key: ${{ secrets.SSH_WALLET_KEY }}
          script: |
            sudo docker pull codewithjass/wallet_app:user-app
            sudo docker pull codewithjass/wallet_app:bank-webhook
            sudo docker-compose down
            sudo docker network inspect app_network >/dev/null 2>&1 || sudo docker network create app_network
            cd walletApp
            sudo docker-compose up

#               environment:
# ER_WEBHOOK_URL}
#       NEXT_PUBLIC_SIGNUP_NETBANKING_URL: ${NEXT_PUBLIC_SIGNUP_NETBANKING_URL}
#       NEXT_PUBLIC_WEBSOCKET_URL: ${NEXT_PUBLIC_WEBSOCKET_      DATABASE_URL: ${DATABASE_URl}
#       NEXTAUTH_URL: ${NEXTAUTH_URL}
#       NEXT_PUBLIC_JWT_SECRET: ${NEXT_PUBLIC_JWT_SECRET}
#       NEXT_PUBLIC_NETBANKING_SECRET: ${NEXT_PUBLIC_NETBANKING_SECRET}
#       NEXT_PUBLIC_NETBANKING_URL: ${NEXT_PUBLIC_NETBANKING_URL}
#       NEXT_PUBLIC_SERVER_WEBHOOK_URL: ${NEXT_PUBLIC_SERVURL}
#       PORT_EXPRESS_WEBHOOK: ${PORT_EXPRESS_WEBHOOK}